name: CLI Publish to Releases

on:
  push:
    branches: [ "main" ]
    paths:
      - src/markdown-cli/**
  workflow_dispatch:

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./src/markdown-cli/
      run: dotnet restore
    - name: Build
      working-directory: ./src/markdown-cli/
      run: dotnet build --no-restore --configuration release
    - name: Test
      working-directory: ./src/markdown-cli/
      run: dotnet test --no-build --verbosity normal --configuration release
    - name: Tag and Release
      working-directory: ./src/markdown-cli/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Read values from the repo
        version="v$(grep '<Version>[0-9].[0-9].[0-9]<\/Version>' ./Morello.MarkdownCli/Markdown.Cli.csproj | grep '[0-9].[0-9].[0-9]' --only-matching)"
        tag="markdown-cli-$version"

        # Config git
        git config user.name "Morello Release Bot"
        git config user.email "releases@morello.tools"

        # Tag
        git tag -a markdown-cli-latest -m "Moves latest tag" --force
        git tag -a $tag -m "Release $tag"
        git push

        # Release
        gh release create $tag --title $version --notes-file ../../docs/markdown-cli/release-notes-$version.md





