name: Console Publish to NuGet

on:
  push:
    branches: [ "main" ]
    paths:
      - src/markdown-console/**

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./src/markdown-console/markdown-console.sln --no-restore --configuration release
    - name: Test
      run: dotnet test ./src/markdown-console/markdown-console.sln --no-build --verbosity normal --configuration release
    - name: Package
      run: dotnet pack ./src/markdown-console/markdown-console.sln --include-symbols --configuration release
    - name: Publish
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: >
        dotnet nuget push ./src/markdown-console/Morello.MarkdownConsole/bin/Release/Morello.MarkdownConsole.*.nupkg
        --api-key "$NUGET_API_KEY"
        --source https://api.nuget.org/v3/index.json
