name: MC Publish to NuGet

on:
  push:
    branches: [ "main" ]
    paths:
      - src/Morello.MarkdownConsole/**

jobs:
  Publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration release
    - name: Package
      run: dotnet pack --include-symbols --configuration release
    - name: Publish
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: >
        dotnet nuget push ./src/Morello.MarkdownConsole/bin/Release/Morello.MarkdownConsole.*.snupkg
        --api-key "$NUGET_API_KEY"
        --source https://api.nuget.org/v3/index.json
