name: .NET

on:
  pull_request:
    branches: [ "main" ]

jobs:
  Build_and_Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration debug
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration debug
    - name: Package
      # We don't use the package in PRs
      # This is simply a test that we can package
      run: dotnet pack --include-symbols --configuration debug
